#######################################################
# 
# DIaSProcess.py
# Python implementation of the Class DIaSProcess
# Generated by Enterprise Architect
# Created on:      24-Oct-2019 10:42:41 AM
# Original author: powen
# 
#######################################################
from DIaSRead import DIaSRead
from DIaSWrite import DIaSWrite


class DIaSProcess:
    """Class: DIaSProcess  By: Phil Owen Date: 10/23/2019 Description: A class that
    contains the main code to ingest and process a data source.
    """
    # The input data definition
    __data_def = None
    # Reference to the dias utils class
    __dias_utils = None
    # Reference to the dias write class
    __dias_write = None
    # Reference to the dias read class
    __dias_read = None

    def __init__(self, data_def: dict):
        """Class constructor.
        """
        self.__data_def = data_def
        self.__dias_write = DIaSWrite(data_def)
        self.__dias_read = DIaSRead(data_def)

        pass

    def process(self, data_def: dict):
        """Main entry point to initiate the processing of the data.
        """
        pass

    def process_file(self):
        """Processes a data file.
        """
        pass

    def download_rawdata(self, url: str):
        """Downloads the raw data using the URL provided.
        """
        pass

    def get_data_file_handle(self, file_path: str, file_name: str):
        """Gets a file handle to a data file.
        """
        pass

    def process_rdbms(self):
        """Processes records in a relational database.
        """
        pass

    def get_data_conn(self, connstr):
        """Obtains a connection to a relational database.
        """
        pass

    def apply_output_rules(self, data_row):
        """Applies the output rules to a data row.
        """
        pass

    def generate_output_record(self, data_row):
        """Generates a output record from a row of data (Node -> Edge -> Node).
        """
        pass
