#######################################################
# 
# DIaSWrite.py
# Python implementation of the Class DIaSWrite
# Generated by Enterprise Architect
# Created on:      24-Oct-2019 10:42:41 AM
# Original author: powen
# 
#######################################################


class DIaSWrite:
    """Class: DIaSWrite  By: Phil Owen Date: 10/23/2019 Description: A class that has
    a number of functions focusing on persisting records for the DIaSProcess class.
    """
    # The data definition
    __data_def = None

    def __init__(self, data_def: dict):
        """Class constructor.
        """
        self.__data_def = data_def
        pass

    def transform(self, data_row: dict):
        """Transforms the data row into the appropriate node-edge-node layout
        """
        pass

    def make_edge(self, edge_data: dict):
        """Makes a KEdge object from the data row passed in.
        """
        pass

    def make_node(self, node_data: dict):
        """Makes a KNode object from the data row passed in.
        """
        pass
