#######################################################
# 
# DIaSUtils.py
# Python implementation of the Class DIaSUtils
# Generated by Enterprise Architect
# Created on:      24-Oct-2019 10:42:41 AM
# Original author: powen
# 
#######################################################


class DIaSUtils:
    """Class: DIaSUtils  By: Phil Owen Date: 10/23/2019 Description: A class that has
    a number of shared utility functions for the DIaSProcess class.
    """
    # The input data record
    __data_row = None

    def __init__(self):
        """Class constructor.
        """
        pass

    def set_data_roww(self, data_row):
        """Sets the data row to be operated on
        """
        self.__data_row = data_row
        pass

    def add_element(self, name: str, value: str):
        """Adds a data element to the data row
        """
        pass

    def convert_to_type(self, data_value: str, new_type: str):
        """Converts a string to the desired data type
        """
        pass

    def make_hyper_edge(self, elements: dict):
        """Creates a unique hyper edge ID from the data passed in.
        """
        pass

    def merge_elements(self, elements: dict, delimiter: str):
        """Merges a list of data elements using the separator provided.
        """
        pass

    def filter_by(self, criteria, criteria_type, filter_operation):
        pass
