#######################################################
# 
# DiaSRead.py
# Python implementation of the Class DIaSRead
# Generated by Enterprise Architect
# Created on:      24-Oct-2019 10:42:41 AM
# Original author: powen
# 
#######################################################


class DIaSRead:
    """Class: DIaSRead  By: Phil Owen Date: 10/23/2019 Description: A class that has a
    number of functions focusing on reading data records for the DIaSProcess class.
    """
    # The input data definition
    __data_def = None

    def __init__(self, data_def: dict):
        """Class constructor
        """
        self.__data_def = data_def
        pass

    def validate_data_def(self):
        """Validates the data definition file.
        """
        pass

    def validate_elements_def(self, data_header: list):
        """Validates the data header definition.
        """
        pass

    def validate_data_row(self, data_row: dict):
        """Validates the properties of a data row.
        """
        pass

    def validate_data_element(self, element_name: str, element_value: str):
        """Validates the data element.
        """
        pass
