#######################################################
# 
# DIaSWrite.py
# Python implementation of the Class DIaSWrite
# Generated by Enterprise Architect
# Created on:      23-Oct-2019 3:32:06 PM
# Original author: powen
# 
#######################################################


class DIaSWrite:
    """Class: DIaSWrite  By: Phil Owen Date: 10/23/2019 Description: A class that has
    a number of functions focusing on persisting records for the DIaSProcess class.
    """
    # The data definition
    _data_def = None

    def __init__(self, data_def):
        """Class constructor.
        """
        self._data_def = data_def
        pass

    def transform(self, data_row):
        pass

    def make_edge(self, edge_data):
        """Makes a KEdge object from the data row passed in.
        """
        pass

    def make_node(self, node_data):
        """Makes a KNode object from the data row passed in.
        """
        pass
