#######################################################
# 
# DIaSProcess.py
# Python implementation of the Class DIaSProcess
# Generated by Enterprise Architect
# Created on:      23-Oct-2019 10:19:43 AM
# Original author: powen
# 
#######################################################


class DIaSProcess:
    """Class: DIaSProcess  By: Phil Owen Date: 10/23/2019 Description: A class that
    contains the main code to ingest and process a data source.
    """
    def __init__(self):
        """Class constructor.
        """
        pass

    def process(self, data_def):
        """Main entry point to initiate the processing of the data.
        """
        pass

    def process_file(self):
        """Processes a data file.
        """
        pass

    def download_rawdata(self, url):
        """Downloads the raw data using the URL provided.
        """
        pass

    def get_data_file_handle(self, file_path, file_name):
        """Gets a file handle to a data file.
        """
        pass

    def process_rdbms(self):
        """Processes records in a relational database.
        """
        pass

    def get_data_conn(self, connstr):
        """Obtains a connection to a relational database.
        """
        pass

    def apply_output_rules(self, data_row):
        """Applies the output rules to a data row.
        """
        pass

    def generate_output_record(self, data_row):
        """Generates a output record from a row of data (Node -> Edge -> Node).
        """
        pass

    def process(self, data_def):
        """Main entry point to initiate the processing of the data.
        """
        pass

    def download_rawdata(self, url):
        """Downloads the raw data using the URL provided.
        """
        pass

    def get_data_file_handle(self, file_path, file_name):
        """Gets a file handle to a data file.
        """
        pass

    def get_data_conn(self, connstr):
        """Obtains a connection to a relational database.
        """
        pass

    def apply_output_rules(self, data_row):
        """Applies the output rules to a data row.
        """
        pass

    def generate_output_record(self, data_row):
        """Generates a output record from a row of data (Node -> Edge -> Node).
        """
        pass