#######################################################
# 
# DiaSRead.py
# Python implementation of the Class DiaSRead
# Generated by Enterprise Architect
# Created on:      23-Oct-2019 3:32:06 PM
# Original author: powen
# 
#######################################################


class DiaSRead:
    """Class: DiaSRead  By: Phil Owen Date: 10/23/2019 Description: A class that has a
    number of functions focusing on reading data records for the DIaSProcess class.
    """
    # The input data definition
    _data_def = None

    def __init__(self, data_def):
        """Class constructor
        """
        self._data_def = data_def
        pass

    def validate_data_def(self):
        """Validates the data definition file.
        """
        pass

    def validate_elements_def(self, data_header):
        """Validates the data header definition.
        """
        pass

    def validate_data_row(self, data_row):
        """Validates the properties of a data row.
        """
        pass

    def validate_data_element(self, element_name, element_value):
        """Validates the data element.
        """
        pass