#######################################################
# 
# DIaSUtils.py
# Python implementation of the Class DIaSUtils
# Generated by Enterprise Architect
# Created on:      23-Oct-2019 3:46:20 PM
# Original author: powen
# 
#######################################################


class DIaSUtils:
    """Class: DIaSUtils  By: Phil Owen Date: 10/23/2019 Description: A class that has
    a number of shared utility functions for the DIaSProcess class.
    """
    # The input data record
    _data_row = None
    def __init__(self, data_row):
        """Class constructor.
        """
        pass

    def add_element(self, name, value):
        """Adds a data element to the data row
        """
        pass

    def convert_to_type(self, data_value, new_type):
        """Converts a string to the desired data type
        """
        pass

    def make_hyper_edge(self, elements):
        """Creates a unique hyper edge ID from the data passed in.
        """
        pass

    def merge_elements(self, elements, delimiter):
        """Merges a list of data elements using the separator provided.
        """
        pass

    def filter_by(self, data_row, criteria, criteria_type, filter_operation):
        pass