#######################################################
# 
# DIUtils.py
# Python implementation of the Class DIUtils
# Generated by Enterprise Architect
# Created on:      15-Nov-2019 11:13:55 AM
# Original author: powen
# 
#######################################################


class DIUtils:
    """Class: DIUtils  By: Phil Owen Date: 15-Nov-2019 Description: A class that has a
    number of utility functions for the DIInspect class.
    """
    def __init__(self):
        pass

    def construct_data_def(self, input_def, output_def):
        """Constructs a data definition file
        """
        pass

    def validate_data_def(self):
        """Validates the data definition
        """
        pass

    def construct_input_def(self, col_def):
        """Creates the input data definition given the results of the introspection.
        """
        pass

    def construct_output_def(self, col_def):
        """Creates the output data definition given the results of the introspection.
        """
        pass

    def inspect_node_type(self, element):
        """Calls a web service to determine if this data value can be associated to a
        biomodel node type.
        """
        pass

    def inspect_edge_predicate(self, element):
        """Calls a web service to determine if this data value can be associated to a
        biomodel edge predicate.
        """
        pass
