#######################################################
# 
# DIWrite.py
# Python implementation of the Class DIWrite
# Generated by Enterprise Architect
# Created on:      15-Nov-2019 11:13:55 AM
# Original author: powen
# 
#######################################################


class DIWrite:
    """Class: DIWrite  By: Phil Owen Date: 15-Nov-2019 Description: A class that has a
    number of functions focusing on persisting records for the DIInspect class.
    """
    # The data definition
    __data_def = None

    def __init__(self, data_def):
        """Class constructor.
        """

        self.__data_def = data_def
        pass

    def write_data_def(self):
        """Writes out the data definition
        """
        pass
