#######################################################
# 
# DPProcess.py
# Python implementation of the Class DPProcess
# Generated by Enterprise Architect
# Created on:      15-Nov-2019 9:10:55 AM
# Original author: powen
# 
#######################################################
from DataProcessing.DPUtils import DPUtils
from DataProcessing.DPRead import  DPRead
from DataProcessing.DPWrite import DPWrite

class DPProcess:
    """Class: DPProcess  By: Phil Owen Date: 10/23/2019 Description: A class that
    contains the main code to ingest and process a data source.
    """

    # The input data definition
    __data_def = None
    # Reference to the dp utils class
    __dp_utils = None
    # Reference to the dias write class
    __dp_write = None
    # Reference to the dias read class
    __dp_read = None

    def __init__(self, data_def):
        """Class constructor.
        """
        self.__data_def = data_def
        self.__dp_write = DPWrite(data_def)
        self.__dp_read = DPRead(data_def)
        self.__dp_utils = DPUtils()
        pass

    def process(self, data_def):
        """Main entry point to initiate the processing of the data.
        """
        pass

    def process_file(self):
        """Processes a data file.
        """
        pass

    def download_rawdata(self, url):
        """Downloads the raw data using the URL provided.
        """
        pass

    def get_data_file_handle(self, file_path, file_name):
        """Gets a file handle to a data file.
        """
        pass

    def process_rdbms(self):
        """Processes records in a relational database.
        """
        pass

    def get_data_conn(self, connstr):
        """Obtains a connection to a relational database.
        """
        pass

    def apply_output_rules(self, data_row):
        """Applies the output rules to a data row.
        """
        pass

    def generate_output_record(self, data_row):
        """Generates a output record from a row of data (Node -> Edge -> Node).
        """
        pass
