#######################################################
# 
# DPRead.py
# Python implementation of the Class DPRead
# Generated by Enterprise Architect
# Created on:      15-Nov-2019 9:10:55 AM
# Original author: powen
# 
#######################################################


class DPRead:
    """Class: DPRead  By: Phil Owen Date: 10/23/2019 Description: A class that has a
    number of functions focusing on reading data records for the DPProcess class.
    """
    # The input data definition
    __data_def = None
    def __init__(self, data_def):
        """Class constructor
        """
        pass

    def validate_data_def(self):
        """Validates the data definition file.
        """
        pass

    def validate_elements_def(self, data_header):
        """Validates the data header definition.
        """
        pass

    def validate_data_row(self, data_row):
        """Validates the properties of a data row.
        """
        pass

    def validate_data_element(self, element_name, element_value):
        """Validates the data element.
        """
        pass