#######################################################
# 
# DPUtils.py
# Python implementation of the Class DPUtils
# Generated by Enterprise Architect
# Created on:      15-Nov-2019 9:10:55 AM
# Original author: powen
# 
#######################################################


class DPUtils:
    """Class: DPUtils  By: Phil Owen Date: 10/23/2019 Description: A class that has a
    number of shared utility functions for the DPProcess class.
    """
    # The input data record
    __data_row = None
    def __init__(self, data_row):
        """Class constructor.
        """
        pass

    def convert_to_type(self, data_value, new_type):
        """Converts a string to the desired data type
        """
        pass

    def make_hyper_edge(self, elements):
        """Creates a unique hyper edge ID from the data passed in.
        """
        pass

    def merge_elements(self, elements, delimiter):
        """Merges a list of data elements using the separator provided.
        """
        pass

    def filter_by(self, data_row, criteria, criteria_type, filter_operation):
        """Filters a data element by some criteria
        """
        pass

    def set_data_row(self, data_row):
        """Sets the data row to be operated on
        """
        pass