#######################################################
# 
# DPWrite.py
# Python implementation of the Class DPWrite
# Generated by Enterprise Architect
# Created on:      15-Nov-2019 11:15:27 AM
# Original author: powen
# 
#######################################################


class DPWrite:
    """Class: DPWrite  By: Phil Owen Date: 15-Nov-2019 Description: A class that has a
    number of functions focusing on persisting records for the DPProcess class.
    """
    # The data definition
    __data_def = None

    def __init__(self, data_def):
        """Class constructor.
        """
        self.__data_def = data_def

        pass

    def transform(self, data_row):
        """Transforms the data row into the appropriate node-edge-node layout
        """
        pass

    def make_edge(self, edge_data):
        """Makes a KEdge object from the data row passed in.
        """
        pass

    def make_node(self, node_data):
        """Makes a KNode object from the data row passed in.
        """
        pass
